### ISSUE TITLE
Database migration system

### ISSUE THREAD

**Issue by p5nbTgip0r** [discord-diabetes/diabot#133]
**Is your feature request related to a problem? Please describe.**
At the moment, there are database migration features in place for moving Redis data to MongoDB and for converting the quote ID data types from `Int64` to `String`. When I created the Redis data migration, I did not foresee more migrations taking place so I didn't design a thorough migration system with expansion in mind. 

Looking back on it, I think this was a mistake because any new data that needs to be stored in MongoDB requires lots of pre-planning as the schema cannot be easily changed after introduction due to the lack of an expandable migration system. This is an unnecessary burden on development in my opinion, and can be solved with the introduction of a system which makes database schema migrations easy to develop, read, and execute.

**Describe the solution you'd like**
A specific handler for database migrations that is executed at startup. The actual migration code will have an incrementally-numbered ID attached to it. Migrations will be executed from the smallest ID to largest ID, and the most recent migration ID ran should be stored in the database. This ID will then be used to skip old migrations which were already ran, only executing new migrations.

**Additional context**
There are some MongoDB migration libraries which may be worth looking into in order to avoid reinventing the wheel.

**Comment by cascer1** [comment]
Try the existing libraries first, writing your first DB migration tooling is *a lot* of work
