### ISSUE TITLE
Add support for non-heroku nightscout instances

### ISSUE THREAD

**Issue by cascer1** [discord-diabetes/diabot#16]
People who don't use Heroku also have rights 😢

**Comment by cascer1** [comment]
Will probably require entering the entire domain as argument, instead of just the heroku subdomain

**Comment by stavlor** [comment]
This appears to be already working, can probably close?

**Comment by cascer1** [comment]
@stavlor the command for accessing another nightscout instance than the one stored for a user still assumes heroku

https://github.com/reddit-diabetes/diabot-discord/blob/f983bb98f098318bbd92493c2fb8d0a9acd1f4b2/src/main/java/com/dongtronic/diabot/commands/NightscoutCommand.kt#L111

**Comment by cascer1** [comment]
**Suggested solution**

To support non-heroku instances, check whether the input is a [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) or not. If it is, use that domain for API requests. If not, assume it's a heroku host.

**Comment by p5nbTgip0r** [comment]
Fixed in #68
