### ISSUE TITLE
Manually calculate delta when it is not part of the nightscout response

### ISSUE THREAD

**Issue by cascer1** [discord-diabetes/diabot#19]
**Is your feature request related to a problem? Please describe.**  
Sometimes the Nightscout entries API endpoint (`/api/v1/entries.json`) does not include a delta. This makes it so that the delta is also not displayed in the NS card (`diabot nightscout`)

**Describe the solution you'd like**  
manually calculate the delta by gathering the two most recent entries and doing some simple math

**Describe alternatives you've considered**  
disabling Dexcom share

**Additional context**  
Original reporter: accio-books

**Comment by stavlor** [comment]
Note: the /pebble endpoint provides an optional extra source for this or we could get entries.json?count=2 possibly.

**Comment by stavlor** [comment]
This should be fixed with #44
