### ISSUE TITLE
Add settings for simple NS cards

### ISSUE THREAD

**Issue by cascer1** [discord-diabetes/diabot#39]
With all the fields we're adding to the Nightscout cards, some users might prefer simple cards that contain only BG data.

`diabot ns setsimple <true/false>`

**Comment by PaperT1D** [comment]
I'm not sure how many different fields are being added or will eventually be added but, if there are going to be several, maybe also have the option to set _which fields_ display? Something like..

`diabot ns setdisplay <trend cob>`

..which would enable the trend and carbs on board fields, and disable any others (such as insulin on board).
