### ISSUE TITLE
Command Simplicity 

### ISSUE THREAD

**Issue by imvaskel** [discord-diabetes/diabot#59]
Doing certain commands (such as diabot ns public true) and diabot ns set (domain name) either don’t help with hinting what to do (diabot simply says Something about a scheme if you don’t put https://) (setting domain) or doesn’t even tell you to put true (setting ns to public)

**Comment by cascer1** [comment]
We should:

1. Determine logical categories for all commands
2. Determine logical command names and aliases
3. Convert all commands to the new system that uses proper subcommands (instead of a bunch of `if`s in one command)

**Comment by cascer1** [comment]
Closing this issue because slash commands will make discoverability and documentation much easier.
