### ISSUE TITLE
Changing the nickname of a new user who joins.

### ISSUE THREAD

**Issue by ad4khd** [discord-diabetes/diabot#86]
I think it would be a pretty good idea to prevent inappropriate names from showing up in the server by changing the nickname of a user when they join. If their name contains an inappropriate word or phrase, it'd simply change their name to "Change your name".

**Comment by cascer1** [comment]
This requires compiling a list of forbidden words that would be pretty easy to get around. So far in the r/Diabetes server the moderation team is usually able to do this quite fast.

**Comment by cascer1** [comment]
83e0f6e3b36b09d475f208a737704ea0eca94297 includes a change that messages new users when their nickname doesn't match the configured guidelines.
