### ISSUE TITLE
Add quote functionality

### ISSUE THREAD

**Issue by esayles** [discord-diabetes/diabot#89]
We've reached the cap on UB3R-B0T quotes and it might be nice to roll that functionality into diabot so we don't do that again. 

This would involve a new command as well as the functionality to watch reactions on recent messages, then a database to store quotes and related metadata. The command and reaction watching could be lifted or inspired from [moiph/ub3rb0t](https://github.com/moiph/ub3r-b0t), and a database as simple as this could be written quickly and hosted free on a MongoDB Atlas server.

**Comment by cascer1** [comment]
Diabot currently uses a Redis database so I'd be interested to see if we can use that for quotes as well so we don't need two databases.
