### ISSUE TITLE
Add Reminders

### ISSUE THREAD

**Issue by librarianmage** [discord-diabetes/diabot#9]
#diabetic-chat paraphrased:

> If diabot can send PMs like other bots can, then potentially set a reminder function to PM for specific times for those doing insulin at specific times. Basically like a timesulin cap but through discord.

> Disclaimer "NOT OUR FAULT IF IT DON'T WORK, DON'T TRUST DUMB INTERNET BOTS TO TAKE CARE OF YOU THX"

**Comment by cascer1** [comment]
Depends on #8

**Comment by cascer1** [comment]
This would require adding a system for reliably keeping track of timed events and making sure they trigger at the correct time. I believe there are other tools that can do this better than diabot ever can. **will not implement.**
